spring.application.name=praktikum5


# Koneksi Database MySQL (Port 3309 sesuai screenshot kamu)
spring.datasource.url=jdbc:mysql://localhost:3309/praktikum6?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=marklee123##
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Konfigurasi JPA / Hibernate
# 'update' akan otomatis membuat/mengupdate tabel di database
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Pengaturan Port Aplikasi (Opsional, standarnya 8080)
server.port=8080

# Pengaturan Upload File (Maksimal 2MB)
spring.servlet.multipart.max-file-size=2MB
spring.servlet.multipart.max-request-size=2MB

# Lokasi Penyimpanan Gambar Secara Statis
spring.web.resources.static-locations=classpath:/static/,file:src/main/resources/static/